version: "3.0"

services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest-alpine
    restart: unless-stopped
    volumes:
      - ./data:/etc/linkding/data
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true
